fixed 28.02.2024
Chousik/Lab5_Kotlin pull request #1
Opened 2024-02-29 10:30 UTC by Chousik

- неправлиьная обработка при вводе пустой команды (выкидывается исключение)
- реализовать CommandHandler через паттерн builder
    - замыкание (что это такое и как через замыкание можно будет реализовать этот паттерн)
- переделать под стиль котлина в целом всю лабу, нужен один стиль
    - принты — использовать принты котлина
    - убрать аннотации throws везде где они не нужны
- поправить все замечания линтера идеи — замечаний не должно быть
- nullable и не nullable типы исправить во всем проекте
- добавить русский языковой пакет в идею
- геттеры и сеттеры без доп логики переписать на свойства
- не создавать отдельный объект коллектора на каждый вызов запроса поля у пользователя
- вынести все магические числа в константы

2024-03-01 16:45 UTC, farid03 requested changes

2024-03-01 16:45 UTC, farid03 commented on src/main/kotlin/commands/ACommand.kt
> +abstract class ACommand(private val _name: String, private val info: String, private val countsArgument: Int) {
Лучше назвать nameValue

2024-03-01 16:45 UTC, farid03 commented on src/main/kotlin/commands/ExecuteCommand.kt
> +        ScriptRecursionValid().valid(args[0])
На каждый вызов метода создаются новые объекты

2024-03-01 16:45 UTC, farid03 commented on src/main/kotlin/handlers/builders/BuilderCommandHandler.kt
> +//    }
?

2024-03-01 16:45 UTC, farid03 commented on src/main/kotlin/handlers/builders/BuilderCommandHandler.kt
> +        }
Можно использовать streamApi

2024-03-01 16:45 UTC, farid03 commented on src/main/kotlin/collection/validators/ValidatorMusicGenre.kt
>          try {
Необязательно ловить исключение, для выбрасывания своего исключения.
Можно обойтись без конструкции try catch

2024-03-01 16:45 UTC, farid03 commented on src/main/kotlin/commands/CountByNumbersOfParticipantsCommand.kt
>              throw ArgumentError("Айди должно быть числом")
Можно обойтись без try catch

2024-03-01 16:45 UTC, farid03 commented on src/main/kotlin/commands/FilterByAlbumsCountCommand.kt
>          }
Можно обойтись без try catch

2024-03-01 16:45 UTC, farid03 commented on src/main/kotlin/commands/HelpCommand.kt
>          }
Можно использовать joinToString

2024-03-01 16:45 UTC, farid03 commented on src/main/kotlin/commands/RemoveByIdCommand.kt
>              throw ArgumentError("Айди должно быть числом")
Можно обойтись без конструкции try catch

2024-03-01 16:45 UTC, farid03 commented on src/main/kotlin/commands/RemoveAtCommand.kt
>              throw ArgumentError("Айди должно быть числом")
Можно обойтись без конструкции try catch

2024-03-01 16:45 UTC, farid03 commented on src/main/kotlin/commands/UpdateCommand.kt
>              throw ArgumentError("Айди должно быть числом")
Можно обойтись без конструкции try catch

2024-03-01 16:45 UTC, farid03 commented on src/main/kotlin/handlers/CollectionControllerMusicBand.kt
>          }
Можно обойтись без конструкции try catch

2024-03-01 16:45 UTC, farid03 commented on src/main/kotlin/handlers/CollectionControllerMusicBand.kt
> +            throw ArgumentError("Группы с таким лидером не существует.")
Можно обойтись без конструкции try catch

2024-03-01 16:45 UTC, farid03 commented on src/main/kotlin/handlers/CollectionControllerMusicBand.kt
>          }
Можно обойтись без конструкции try catch

2024-03-01 16:45 UTC, farid03 commented on src/main/kotlin/handlers/RunHandler.kt
>          } catch (e: InvalidCommandError) {
Можно объединить :)

2024-03-01 16:45 UTC, farid03 commented on src/main/kotlin/handlers/RunHandler.kt
>          } catch (e: InvalidCommandError) {
Можно объединить

2024-03-01 16:45 UTC, farid03 commented on src/main/kotlin/Main.kt
>          commandHandler.addCommand("execute", ExecuteCommand(runHandlerMain))
Почему часть команд в commandHandler добавляется отдельно?

2024-03-01 17:08 UTC, farid03 requested changes

2024-03-01 17:08 UTC, farid03 commented on src/main/kotlin/handlers/builders/BuilderCommandHandler.kt
> +    private fun add(commandName: String, aCommand: ACommand) {
Логично будет сделать чтобы тоже возвращался builder

2024-03-01 17:08 UTC, farid03 commented on src/main/kotlin/handlers/builders/BuilderCommandHandler.kt
> +class BuilderCommandHandler(private val commands: HashMap<String, ACommand> = HashMap()) {
CommandHandlerBuilder подходит больше
Все классы реализующие данный паттерн называют обычно так - слово builder идет в конце

2024-03-13 10:42 UTC, farid03 commented on src/main/kotlin/collection/validators/ValidatorMusicGenre.kt
> +        MusicGenre.valueOf(t.toString())
!! operator

2024-03-13 10:42 UTC, farid03 commented on src/main/kotlin/commands/ExecuteCommand.kt
> +class ExecuteCommand(private var runHandler: RunHandler, private val scriptFileValidator: ScriptFileValidator = ScriptFileValidator(), private val scriptRecursionValid: ScriptRecursionValid = ScriptR
Разумнее сделать что-то из этих вариантов:
- честные приватные переменные, полный конструктор нигде не используется
- прокидывать объект в контекст через конструктор и не создавать тут

2024-03-13 10:43 UTC, farid03 commented on src/main/kotlin/Main.kt
>          commandHandler.addCommand("execute", ExecuteCommand(runHandlerMain))
Избавиться от циклической зависимости

2024-03-15 14:07 UTC, Chousik commented
Lab5 ready.

2024-03-15 14:08 UTC, merged